import Head from 'next/head'
import Navbar from '../components/Navbar'
import Letter from '../components/Letter'
import {lettersData} from '../data/data.js'


export async function getStaticProps() {

  return {
    props : {
      letters: lettersData,
    },
  }
}

export default function Letters({ letters }) {
  return (
    <div>
      <Head>
        <title>Cartas para Nise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" size="32x32" type="image/png" href="/assets/mail.png" />
      </Head>
      <div className="letters-background h-screen overflow-auto">
        {/* <Navbar/> */}
        <div className="text-center pt-10">
          <h1>Cartas</h1>
        </div>
        {letters.map((letter) => (
          <Letter
            key={letter.letterId}
            link={`/cartas/${letter.letterId.toString()}`}
            title={letter.title}
            text={letter.description}
          ></Letter>
        ))}
      </div>
    </div>
  )
}

