import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'
import Letter from '../components/Letter'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cartas para Nise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" size="32x32" type="image/png" href="/assets/mail.png" />
      </Head>
      {/* <Navbar/> */}
      <div className="letters-background">
        <div className="text-center pt-10">
          <h1>Cartas</h1>
        </div>
        <Letter/>
        <Letter/>
        <Letter/>
        <Letter/>
      </div>
    </div>
  )
}