import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import Main from '../components/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Cartas para Nise</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" size="32x32" type="image/png" href="/assets/mail.png" />
      </Head>
      {/* <Navbar/> */}
      <Main/>
    </div>
  )
}
